"""Valeurs marchandes des effectifs Premier League 2025/26, en millions d'euros.

Repris tel quel de algo/CLUBS_LOGISTIC_REGRESSION.ipynb (dict maintenu à la main, à mettre
à jour à chaque fenêtre de transferts). Utilisé par src/features/market_value_injuries.py
pour pondérer l'impact des absences dans src/models/predict.py.
"""

SQUAD_VALUES: dict[str, dict[str, float]] = {
    "Arsenal": {"Bukayo Saka": 150, "Viktor Gyokeres": 90, "Declan Rice": 110, "William Saliba": 90, "Gabriel Magalhaes": 80, "Martin Odegaard": 80, "Kai Havertz": 75, "Gabriel Martinelli": 65, "Martin Zubimendi": 60, "Jurrien Timber": 65, "Ben White": 60, "Noni Madueke": 50, "Leandro Trossard": 45, "Riccardo Calafiori": 45, "David Raya": 40, "Piero Hincapie": 40, "Mikel Merino": 40, "Ethan Nwaneri": 40, "Gabriel Jesus": 30, "Cristhian Mosquera": 25, "Jakub Kiwior": 20, "Kepa Arrizabalaga": 15},
    "Aston Villa": {"Morgan Rogers": 80, "Ollie Watkins": 75, "Jhon Duran": 65, "Leon Bailey": 55, "Ezri Konsa": 50, "Pau Torres": 45, "Ian Maatsen": 40, "Moussa Diaby": 40, "Boubacar Kamara": 40, "Emiliano Martinez": 40, "Marcus Rashford": 30, "John McGinn": 30, "Youri Tielemans": 30, "Matty Cash": 25, "Lucas Digne": 15},
    "Bournemouth": {"Dean Huijsen": 55, "Justin Kluivert": 55, "Evanilson": 55, "Antoine Semenyo": 40, "Ilya Zabarnyi": 40, "Dango Ouattara": 35, "Marcos Senesi": 30, "Luis Sinisterra": 25, "Tyler Adams": 20, "James Hill": 20, "Marcus Tavernier": 20, "Ryan Christie": 15, "Lewis Cook": 15},
    "Brentford": {"Igor Thiago": 40, "Nathan Collins": 40, "Kevin Schade": 35, "Sepp van den Berg": 35, "Keane Lewis-Potter": 30, "Christian Norgaard": 30, "Mark Flekken": 25, "Kristoffer Ajer": 25, "Mathias Jensen": 25, "Ethan Pinnock": 25, "Ben Mee": 10},
    "Brighton": {"Kaoru Mitoma": 80, "Georginio Rutter": 55, "Carlos Baleba": 55, "Jan Paul van Hecke": 50, "Simon Adingra": 50, "Matt O'Riley": 45, "Facundo Buonanotte": 40, "Bart Verbruggen": 40, "Julio Enciso": 40, "Igor": 35, "Pervis Estupinan": 30, "Danny Welbeck": 15},
    "Burnley": {"Wilson Odobert": 30, "Maxime Esteve": 25, "Zeki Amdouni": 25, "James Trafford": 20, "Lyle Foster": 20, "Josh Cullen": 20, "Luca Koleosho": 20, "Dara O'Shea": 20, "Aaron Ramsey": 15, "Jaidon Anthony": 15, "CJ Egan-Riley": 15, "Michael Obafemi": 12, "Shumaira Mheuka": 10},
    "Chelsea": {"Cole Palmer": 110, "Moises Caicedo": 110, "Enzo Fernandez": 90, "Estevao Willian": 80, "Joao Pedro": 75, "Reece James": 60, "Pedro Neto": 60, "Levi Colwill": 50, "Marc Cucurella": 50, "Andrey Santos": 45, "Alejandro Garnacho": 40, "Jorrel Hato": 35, "Malo Gusto": 35, "Jamie Gittens": 35, "Romeo Lavia": 25, "Robert Sanchez": 20, "Filip Jorgensen": 15},
    "Crystal Palace": {"Eberechi Eze": 80, "Marc Guehi": 65, "Jean-Philippe Mateta": 55, "Adam Wharton": 50, "Joachim Andersen": 40, "Cheick Doucoure": 35, "Evann Guessand": 28, "Edward Nketiah": 18, "Ismaila Sarr": 30, "Daniel Munoz": 30, "Tyrick Mitchell": 25, "Sam Johnstone": 20, "Will Hughes": 20, "Jefferson Lerma": 20, "Borna Sosa": 4, "Jeffrey Schlupp": 15},
    "Everton": {"Jarrad Branthwaite": 65, "Jordan Pickford": 35, "Dwight McNeil": 30, "Beto": 25, "Vitaliy Mykolenko": 20, "James Tarkowski": 20, "Jack Harrison": 20, "Nathan Patterson": 15, "Idrissa Gana Gueye": 15, "Abdoulaye Doucoure": 15, "Dominic Calvert-Lewin": 15, "Seamus Coleman": 5},
    "Fulham": {"Rodrigo Muniz": 50, "Alex Iwobi": 35, "Antonee Robinson": 35, "Andreas Pereira": 30, "Calvin Bassey": 30, "Manor Solomon": 25, "Sasa Lukic": 20, "Bernd Leno": 20, "Harrison Reed": 20, "Harry Wilson": 20, "Kenny Tete": 15, "Tom Cairney": 15, "Raul Jimenez": 15, "Adama Traore": 20},
    "Leeds": {"Crysencio Summerville": 50, "Wilfried Gnonto": 30, "Pascal Struijk": 25, "Joe Rodon": 25, "Joel Piroe": 25, "Illan Meslier": 20, "Daniel James": 20, "Junior Firpo": 15, "Patrick Bamford": 15, "Sam Byram": 10},
    "Liverpool": {"Alexander Isak": 145, "Florian Wirtz": 125, "Hugo Ekitike": 95, "Alexis Mac Allister": 90, "Luis Diaz": 85, "Dominik Szoboszlai": 80, "Cody Gakpo": 70, "Ryan Gravenberch": 65, "Ibrahima Konate": 60, "Mohamed Salah": 55, "Darwin Nunez": 50, "Milos Kerkez": 45, "Jeremie Frimpong": 40, "Diogo Jota": 40, "Alisson": 20, "Virgil van Dijk": 30, "Andrew Robertson": 25, "Joe Gomez": 20, "Caoimhin Kelleher": 20},
    "Man City": {"Erling Haaland": 200, "Josko Gvardiol": 90, "Phil Foden": 80, "Tijjani Reijnders": 65, "Rayan Cherki": 65, "Rodri": 65, "Jeremy Doku": 65, "Ruben Dias": 65, "Savinho": 65, "Bernardo Silva": 60, "Rayan Ait-Nouri": 50, "Matheus Nunes": 40, "Oscar Bobb": 35, "Rico Lewis": 35, "John Stones": 30, "Gianluigi Donnarumma": 25, "James Trafford": 20, "Stefan Ortega": 8},
    "Man United": {"Bryan Mbeumo": 80, "Benjamin Sesko": 65, "Kobbie Mainoo": 50, "Amad Diallo": 50, "Leny Yoro": 50, "Bruno Fernandes": 40, "Lisandro Martinez": 40, "Matthijs de Ligt": 40, "Manuel Ugarte": 35, "Patrick Dorgu": 35, "Diogo Dalot": 30, "Andre Onana": 30, "Noussair Mazraoui": 20, "Mason Mount": 20, "Luke Shaw": 20, "Casemiro": 10},
    "Newcastle": {"Bruno Guimaraes": 90, "Sandro Tonali": 80, "Anthony Gordon": 80, "Nick Woltemade": 65, "Tino Livramento": 45, "Malick Thiaw": 45, "Anthony Elanga": 40, "Harvey Barnes": 40, "Jacob Ramsey": 35, "Joelinton": 35, "Yoane Wissa": 30, "Lewis Hall": 30, "Nick Pope": 25, "Kieran Trippier": 20, "Fabian Schar": 20, "Dan Burn": 15, "Sean Longstaff": 15},
    "Nott'm Forest": {"Morgan Gibbs-White": 55, "Murillo": 45, "Ibrahim Sangare": 35, "Elliot Anderson": 30, "Callum Hudson-Odoi": 30, "Nuno Tavares": 25, "Nikola Milenkovic": 25, "Matz Sels": 20, "Neco Williams": 20, "Ryan Yates": 20, "Andrew Omobamidele": 20, "Nicolas Dominguez": 20, "Ola Aina": 20, "Chris Wood": 20},
    "Sunderland": {"Jobe Bellingham": 30, "Jack Clarke": 20, "Wilson Isidor": 20, "Pierre Ekwah": 20, "Romaine Mundle": 20, "Chris Rigg": 18, "Dan Ballard": 15, "Salis Abdul Samed": 15, "Trai Hume": 12, "Anthony Patterson": 12, "Eliezer Mayenda": 12, "Dennis Cirkin": 10, "Patrick Roberts": 8},
    "Tottenham": {"Xavi Simons": 75, "Mohammed Kudus": 70, "Micky van de Ven": 65, "Pape Matar Sarr": 60, "Cristian Romero": 60, "Dejan Kulusevski": 55, "Dominic Solanke": 50, "Brennan Johnson": 50, "Destiny Udogie": 50, "Archie Gray": 45, "Pedro Porro": 45, "Guglielmo Vicario": 40, "Joao Palhinha": 35, "James Maddison": 35, "Yves Bissouma": 30, "Kevin Danso": 25, "Rodrigo Bentancur": 25, "Radu Dragusin": 20},
    "West Ham": {"Lucas Paqueta": 65, "Jarrod Bowen": 60, "Jean-Clair Todibo": 40, "Edson Alvarez": 40, "Niclas Fullkrug": 30, "James Ward-Prowse": 25, "Aaron Wan-Bissaka": 20, "Konstantinos Mavropanos": 25, "Tomas Soucek": 20, "Carlos Soler": 20, "Kurt Zouma": 15, "Emerson Palmieri": 15, "Alphonse Areola": 15},
    "Wolves": {"Matheus Cunha": 70, "Joao Gomes": 35, "Hwang Hee-chan": 35, "Boubacar Traore": 30, "Emmanuel Agbadou": 25, "Nelson Semedo": 25, "Jose Sa": 25, "Tommy Doyle": 20, "Mario Lemina": 20, "Toti Gomes": 20, "Pablo Sarabia": 15, "Luke Cundle": 15},
}
