"""Valeurs marchandes des effectifs Premier League, en millions d'euros.

Source : transfermarkt.co.uk, effectifs et valeurs saison 2026/27 (recupere le 2026-08-12).
Couvre les 20 clubs de Premier League pour la saison 2026/27. Burnley, West Ham et Wolves
ont ete relegues en Championship a l'issue de 2025/26 et sont remplaces ici par les 3
clubs promus : Ipswich, Coventry et Hull. Ces 3 derniers n'ont pas ou peu d'historique
dans le dataset d'entrainement (features Elo/classement/forme peu ou pas fiables pour
eux en l'etat), donc predict.py ne devrait pas encore etre utilise pour leurs matchs.

A remettre a jour a chaque fenetre de transferts. Utilise par
src/features/market_value_injuries.py pour ponderer l'impact des absences dans
src/models/predict.py.
"""

SQUAD_VALUES: dict[str, dict[str, float]] = {
    "Arsenal": {"David Raya": 30, "Illan Meslier": 8, "Kepa Arrizabalaga": 5, "Tommy Setford": 0.5, "William Saliba": 100, "Gabriel": 75, "Piero Hincapie": 50, "Cristhian Mosquera": 40, "Riccardo Calafiori": 55, "Myles Lewis-Skelly": 45, "Jurrien Timber": 70, "Ben White": 30, "Martin Zubimendi": 75, "Declan Rice": 120, "Bruno Guimaraes": 70, "Mikel Merino": 25, "Martin Odegaard": 70, "Eberechi Eze": 65, "Ethan Nwaneri": 35, "Fabio Vieira": 18, "Gabriel Martinelli": 45, "Christos Tzolis": 40, "Reiss Nelson": 8, "Bukayo Saka": 110, "Noni Madueke": 50, "Max Dowman": 30, "Viktor Gyokeres": 65, "Kai Havertz": 55, "Gabriel Jesus": 17},
    "Aston Villa": {"Emiliano Martinez": 12, "Marco Bizot": 1.5, "Ezri Konsa": 45, "Pau Torres": 20, "Modou Keba Cisse": 6, "Victor Lindelof": 5, "Tyrone Mings": 3, "Ian Maatsen": 30, "Matty Cash": 22, "Kosta Nedeljkovic": 6, "Amadou Onana": 45, "Boubacar Kamara": 40, "Lamare Bogarde": 18, "Joao Gomes": 40, "John McGinn": 13, "Ross Barkley": 4, "Johan Manzambi": 65, "Alejandro Garnacho": 28, "Emiliano Buendia": 16, "Samuel Iling-Junior": 6.5, "Evann Guessand": 25, "Leon Bailey": 14, "Alysson": 10, "Ollie Watkins": 25, "Tammy Abraham": 18, "Brian Madjo": 12},
    "Bournemouth": {"Djordje Petrovic": 28, "Fraser Forster": 0.4, "Will Dennis": 0.325, "Antonio Silva": 25, "Bafode Diakite": 25, "James Hill": 23, "Veljko Milosavljevic": 20, "Matai Akinmboni": 1, "Adrien Truffert": 30, "Julio Soler": 8, "Juanlu Sanchez": 10, "Julian Araujo": 8, "Max Aarons": 2.5, "Adam Smith": 0.3, "Tyler Adams": 25, "Ben Winterburn": 0.35, "Alex Scott": 50, "Alex Toth": 12, "Lewis Cook": 11, "Ryan Christie": 8, "Marcus Tavernier": 25, "Justin Kluivert": 25, "Amine Adli": 20, "Rayan": 60, "Ben Gannon-Doak": 15, "David Brooks": 12, "Junior Kroupi": 70, "Evanilson": 35, "Alvaro Rodriguez": 10, "Enes Unal": 7, "Daniel Jebbison": 6},
    "Brentford": {"Caoimhin Kelleher": 28, "Hakon Valdimarsson": 2.5, "Ellery Balcombe": 0.4, "Sepp van den Berg": 32, "Nathan Collins": 30, "Kristoffer Ajer": 22, "Jannik Schuster": 18, "Ethan Pinnock": 3, "Ji-soo Kim": 1.8, "Benjamin Fredrick": 0.6, "Benjamin Arthur": 0.1, "Rico Henry": 13, "Jayden Meghoma": 2, "Michael Kayode": 40, "Aaron Hickey": 16, "Vitaly Janelt": 16, "Yunus Konak": 3.5, "Mamadou Sangare": 40, "Yegor Yarmolyuk": 32, "Mathias Jensen": 10, "Josh Dasilva": 1.5, "Keane Lewis-Potter": 25, "Mikkel Damsgaard": 30, "Antoni Milambo": 15, "Fabio Carvalho": 8, "Kevin Schade": 35, "Jaidon Anthony": 20, "Gustavo Nunes": 8, "Dango Ouattara": 35, "Igor Thiago": 65, "Kaye Furo": 8, "Callum Wilson": 4},
    "Brighton": {"Bart Verbruggen": 40, "Jason Steele": 0.5, "Tom McGill": 0.5, "Luka Vuskovic": 60, "Pascal Struijk": 22, "Olivier Boscagli": 15, "Igor Julio": 10, "Eiran Cashin": 5, "Michael Svoboda": 3.5, "Lewis Dunk": 3.5, "Ferdi Kadioglu": 35, "Maxim De Cuyper": 22, "Mats Wieffer": 25, "Costinha": 7, "Carlos Baleba": 55, "Jack Hinshelwood": 28, "Yasin Ayari": 40, "Diego Gomez": 25, "Matt O'Riley": 18, "Malick Yalcouye": 12, "Pascal Gross": 2.5, "Kaoru Mitoma": 22, "Ibrahim Osman": 7, "Yankuba Minteh": 45, "Zadok Yohanna": 18, "Amario Cozier-Duberry": 5, "Georginio Rutter": 30, "Charalampos Kostoulas": 25, "Evan Ferguson": 20, "Stefanos Tzimas": 18},
    "Chelsea": {"Mike Penders": 25, "Robert Sanchez": 22, "Gabriel Slonina": 3, "Teddy Sharman-Lowe": 0.5, "Maxence Lacroix": 50, "Levi Colwill": 50, "Wesley Fofana": 28, "Mamadou Sarr": 22, "Tosin Adarabioyo": 16, "Axel Disasi": 15, "Benoit Badiashile": 15, "Aaron Anselmino": 10, "Jorrel Hato": 40, "Pep Chavarria": 10, "Caleb Wiley": 8, "Reece James": 60, "Marco Palestra": 35, "Malo Gusto": 35, "Josh Acheampong": 25, "Moises Caicedo": 100, "Romeo Lavia": 22, "Dario Essugo": 15, "Enzo Fernandez": 100, "Valentin Barco": 40, "Jordan Henderson": 1.2, "Morgan Rogers": 110, "Cole Palmer": 100, "Jamie Gittens": 30, "Estevao": 80, "Pedro Neto": 60, "Geovany Quenda": 42, "Joao Pedro": 80, "Nicolas Jackson": 40, "Liam Delap": 28, "Emmanuel Emegha": 25, "Marc Guiu": 12, "David Datro Fofana": 4, "Dastan Satpaev": 3.5, "Danny Welbeck": 3},
    "Crystal Palace": {"Dean Henderson": 28, "Walter Benitez": 4, "Remi Matthews": 0.2, "Jaydee Canvot": 28, "Chris Richards": 28, "Chadi Riad": 20, "Takehiro Tomiyasu": 5, "Tyrick Mitchell": 25, "Borna Sosa": 3, "Daniel Munoz": 22, "Oscar Mingueza": 18, "Caleb Kporha": 1, "Adam Wharton": 70, "Cheick Doucoure": 10, "Jefferson Lerma": 6, "David Ozoh": 2.2, "Will Hughes": 5, "Justin Devenny": 12, "Daichi Kamada": 10, "Matheus Franca": 6, "Dwight McNeil": 18, "Ismaila Sarr": 45, "Yeremy Pino": 30, "Romain Esse": 10, "Jesurun Rak-Sakyi": 6, "Jorgen Strand Larsen": 40, "Jean-Philippe Mateta": 30, "Eddie Nketiah": 10},
    "Everton": {"Jordan Pickford": 13, "Mark Travers": 3, "Tom King": 0.1, "Jarrad Branthwaite": 40, "James Tarkowski": 5, "Michael Keane": 3, "Vitaliy Mykolenko": 25, "Adam Aznou": 6, "Jake O'Brien": 18, "Nathan Patterson": 10, "James Garner": 45, "Hayden Hackney": 32, "Christian Norgaard": 5, "Kiernan Dewsbury-Hall": 35, "Tim Iroegbunam": 18, "Carlos Alcaraz": 15, "Harrison Armstrong": 12, "Merlin Rohl": 16, "Tyrique George": 20, "Iliman Ndiaye": 55, "Brennan Johnson": 30, "Tyler Dibling": 17, "Thierno Barry": 30, "Beto": 18},
    "Fulham": {"Bernd Leno": 6, "Benjamin Lecomte": 0.8, "Calvin Bassey": 28, "Joachim Andersen": 20, "Jorge Cuenca": 8, "Ryan Sessegnon": 22, "Antonee Robinson": 22, "Kenny Tete": 8, "Timothy Castagne": 8, "Sander Berge": 25, "Shea Charles": 15, "Harrison Reed": 2, "Tom Cairney": 0.5, "Josh King": 25, "Emile Smith Rowe": 20, "Cesar Palacios": 7.5, "Kevin": 25, "Alex Iwobi": 20, "Oscar Bobb": 28, "Gonzalo Garcia": 30, "Rodrigo Muniz": 20, "Jonah Kusi-Asare": 3},
    "Leeds": {"James Trafford": 25, "Lucas Perri": 10, "Alex Cairns": 0.05, "Tarik Muharemovic": 35, "Jaka Bijol": 20, "Joe Rodon": 18, "Sebastiaan Bornauw": 8, "Gabriel Gudmundsson": 20, "Sam Byram": 0.4, "Jayden Bogle": 15, "James Justin": 12, "Ethan Ampadu": 30, "Anton Stach": 28, "Ilia Gruev": 12, "Sean Longstaff": 15, "Ao Tanaka": 13, "Brenden Aaronson": 22, "Noah Okafor": 25, "Largie Ramazani": 8, "Harry Wilson": 25, "Wilfried Gnonto": 16, "Daniel James": 10, "Dominic Calvert-Lewin": 22, "Joe Gelhardt": 14, "Joel Piroe": 10, "Lukas Nmecha": 10, "Mateo Joseph": 3.5},
    "Liverpool": {"Giorgi Mamardashvili": 28, "Alisson": 15, "Vitezslav Jaros": 5, "Freddie Woodman": 3, "Harvey Davies": 0.5, "Jeremy Jacquet": 55, "Giovanni Leoni": 25, "Ronald Araujo": 20, "Virgil van Dijk": 15, "Joe Gomez": 13, "Milos Kerkez": 35, "Konstantinos Tsimikas": 4.5, "Jeremie Frimpong": 35, "Conor Bradley": 25, "Calvin Ramsay": 1.5, "Ryan Gravenberch": 80, "Wataru Endo": 4, "Stefan Bajcetic": 4, "Alexis Mac Allister": 70, "Curtis Jones": 35, "Trey Nyoni": 8, "Florian Wirtz": 100, "Dominik Szoboszlai": 100, "Harvey Elliott": 20, "Cody Gakpo": 60, "Victor Munoz": 30, "Rio Ngumoha": 30, "Federico Chiesa": 13, "Alexander Isak": 85, "Hugo Ekitike": 80},
    "Man City": {"Gianluigi Donnarumma": 45, "Marcus Bettinelli": 0.3, "Marc Guehi": 70, "Josko Gvardiol": 70, "Ruben Dias": 55, "Abdukodir Khusanov": 50, "Vitor Reis": 30, "Juma Bah": 10, "Max Alleyne": 8, "Nico O'Reilly": 70, "Rayan Ait-Nouri": 40, "Josh Wilson-Esbrand": 2.5, "Matheus Nunes": 50, "Rico Lewis": 28, "Issa Kabore": 4, "Rodri": 55, "Nico Gonzalez": 40, "Elliot Anderson": 110, "Tijjani Reijnders": 50, "Mateo Kovacic": 10, "Rayan Cherki": 90, "Phil Foden": 70, "Claudio Echeverri": 15, "Jeremy Doku": 75, "Savinho": 35, "Jack Grealish": 20, "Jeremy Monga": 15, "Antoine Semenyo": 80, "Erling Haaland": 220, "Omar Marmoush": 50},
    "Man United": {"Senne Lammens": 35, "Karl Darlow": 0.2, "Tom Heaton": 0.1, "Leny Yoro": 50, "Lisandro Martinez": 45, "Matthijs de Ligt": 30, "Ayden Heaven": 30, "Harry Maguire": 8, "Patrick Dorgu": 35, "Luke Shaw": 8, "Harry Amass": 7, "Diogo Dalot": 30, "Noussair Mazraoui": 18, "Andrey Santos": 40, "Manuel Ugarte": 25, "Toby Collyer": 5, "Kobbie Mainoo": 70, "Youri Tielemans": 40, "Tyler Fletcher": 1.5, "Bruno Fernandes": 35, "Mason Mount": 25, "Jack Fletcher": 1.5, "Marcus Rashford": 40, "Bryan Mbeumo": 75, "Amad Diallo": 45, "Shea Lacey": 5, "Matheus Cunha": 75, "Benjamin Sesko": 75, "Joshua Zirkzee": 20},
    "Newcastle": {"Lukas Hornicek": 18, "Ewen Jaouen": 12, "Nick Pope": 5, "Aidan Harris": 0.2, "Mark Gillespie": 0.1, "Malick Thiaw": 45, "Sven Botman": 35, "Fabian Schar": 4, "Dan Burn": 4, "Lewis Hall": 40, "Tino Livramento": 45, "Aladji Bamba": 18, "Jacob Ramsey": 35, "Joelinton": 25, "Lewis Miley": 25, "Joe Willock": 14, "Sean Steur": 7, "Bazoumana Toure": 50, "Harvey Barnes": 32, "Anthony Elanga": 32, "Jacob Murphy": 12, "Nick Woltemade": 55, "William Osula": 28, "Yoane Wissa": 25},
    "Nott'm Forest": {"John Victor": 5, "Matz Sels": 3.5, "Murillo": 50, "Ousmane Diomande": 42, "Nikola Milenkovic": 28, "Jair Cunha": 15, "Morato": 14, "Zach Abbott": 4, "Tyler Bindon": 3.5, "Neco Williams": 28, "Luca Netz": 8, "Omar Richards": 2, "Ola Aina": 18, "Nicolo Savona": 15, "Eric da Silva Moreira": 0.8, "Ibrahim Sangare": 20, "Nicolas Dominguez": 15, "Xaver Schlager": 10, "Ryan Yates": 7, "Morgan Gibbs-White": 70, "James McAtee": 18, "Callum Hudson-Odoi": 30, "Dan Ndoye": 32, "Omari Hutchinson": 30, "Dilane Bakwa": 28, "Arnaud Kalimuendo": 25, "Igor Jesus": 25, "Taiwo Awoniyi": 8, "Chris Wood": 5},
    "Sunderland": {"Robin Roefs": 28, "Melker Ellborg": 3, "Simon Moore": 0.075, "Dan Ballard": 20, "Omar Alderete": 13, "Jenson Seelt": 5, "Luke O'Nien": 0.7, "Aji Alese": 0.7, "Reinildo Mandava": 4, "Trai Hume": 22, "Nordi Mukiele": 16, "Thomas Meunier": 1.5, "Granit Xhaka": 8, "Habib Diarra": 35, "Noah Sadiki": 35, "Enzo Le Fee": 28, "Alan Browne": 2, "Abdoullah Ba": 1.5, "Chris Rigg": 25, "Simon Adingra": 22, "Nilson Angulo": 17, "Romaine Mundle": 7, "Chemsdine Talbi": 25, "Jocelin Ta Bi": 2.5, "Brian Brobbey": 40, "Wilson Isidor": 18, "Luis Semedo": 0.6},
    "Tottenham": {"Guglielmo Vicario": 18, "Antonin Kinsky": 15, "Martin Dubravka": 0.5, "Brandon Austin": 0.5, "Jan Paul van Hecke": 60, "Cristian Romero": 50, "Micky van de Ven": 50, "Marcos Senesi": 25, "Kevin Danso": 20, "Ashley Phillips": 7, "Kota Takai": 5, "Ben Davies": 3, "Destiny Udogie": 30, "Souza": 12, "Andrew Robertson": 7, "Pedro Porro": 45, "Djed Spence": 40, "Sandro Tonali": 80, "Archie Gray": 35, "Rodrigo Bentancur": 20, "Mateus Fernandes": 50, "Lucas Bergvall": 35, "Conor Gallagher": 32, "Pape Matar Sarr": 30, "Xavi Simons": 40, "James Maddison": 20, "Dejan Kulusevski": 17, "Wilson Odobert": 18, "Mikey Moore": 18, "Mohammed Kudus": 50, "Min-hyeok Yang": 3, "Dominic Solanke": 28, "Richarlison": 25, "Mathys Tel": 22, "Dane Scarlett": 1.5},
    "Coventry": {"Carl Rushworth": 16, "Oliver Dovin": 2, "Ben Wilson": 0.3, "Bobby Thomas": 16, "Liam Kitching": 14, "Aurele Amenda": 10, "Joel Latibeaudiere": 3, "Luke Woolfenden": 2, "Jay Dasilva": 9, "Miguel Angel Brau": 1, "Jake Bidwell": 0.6, "Milan van Ewijk": 22, "Kaine Kesler-Hayden": 3, "Matt Grimes": 5, "Caleb Yirenkyi": 18, "Victor Torp": 14, "Josh Eccles": 9, "Frank Onyeka": 8, "Kai Andrews": 0.5, "Ephron Mason-Clark": 16, "Jack Rudoni": 20, "Raphael Borges Rodrigues": 0.45, "Loum Tchaouna": 13, "Tatsuhiro Sakamoto": 4.5, "Haji Wright": 16, "Brandon Thomas-Asante": 16, "Ellis Simms": 12},
    "Hull": {"Konstantinos Tzolakis": 18, "Jack Butland": 1.5, "Dillon Phillips": 0.2, "Charlie Hughes": 10, "Paddy McNair": 1.5, "John Egan": 1, "Semi Ajayi": 0.7, "Ryan Giles": 12, "Matt Targett": 3, "Matty Jacob": 0.4, "Cody Drameh": 3, "Lewie Coyle": 1.2, "Regan Slater": 5.5, "Oscar Zambrano": 1.5, "Jens Hjerto-Dahl": 10, "Hidemasa Morita": 8, "Darko Gyabi": 2, "Eliot Matazo": 1.5, "Matt Crooks": 0.7, "Abdulkadir Omur": 1.5, "Elliot Stroud": 8, "Kieran Dowell": 0.6, "Liam Millar": 5, "Mohamed Belloumi": 6, "David Akintola": 1, "Oli McBurnie": 5, "Enis Destan": 2},
    "Ipswich": {"Kjell Scherpen": 8, "Christian Walton": 2.5, "Kayne van Oevelen": 2, "Alex Palmer": 1, "David Button": 0.05, "Dara O'Shea": 16, "Jacob Greaves": 14, "Issa Diop": 8, "Cedric Kipre": 2, "Leif Davis": 20, "Ben Johnson": 6, "Harry Clarke": 2.5, "Darnell Furlong": 2.5, "Florentino": 16, "Azor Matusiwa": 12, "Marcelino Nunez": 14, "Sasa Lukic": 10, "Jack Taylor": 3, "Cameron Humphreys": 0.6, "Kasey McAteer": 10, "Anis Mehmeti": 15, "Jaden Philogene": 20, "Jack Clarke": 20, "Daizen Maeda": 13, "Abdul Fatawu": 20, "Sindre Walle Egeli": 15, "Chiedozie Ogbene": 4, "George Hirst": 10, "Emersonn": 8, "Chuba Akpom": 3.5, "Ali Al-Hamadi": 1.5},
}
